vim.keymap.set('n', '<leader>fe', '<cmd>Ex<cr>', { desc = 'Open NETRW' })
vim.keymap.set({'i', 'n', 'v'}, '<C-c>', '<Esc>', { desc = 'Map <C-c> to <Esc>' })
vim.keymap.set('n', '<C-c>', '<cmd>nohlsearch<cr>', { desc = 'Clear search highlighting with <C-c>' })
vim.keymap.set("v", "<C-j>", ":m '>+1<CR>gv=gv", { desc = 'Move selection down 1 line' })
vim.keymap.set("v", "<C-k>", ":m '<-2<CR>gv=gv", { desc = 'Move selection up 1 line' })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = 'Jump down half a page' })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = 'Jump up half a page' })
vim.keymap.set("x", "<leader>p", [["_dP]], { desc = 'Paste without yanking' })
vim.keymap.set('n', '<C-j>', '<C-w>j', { desc = 'Jump to bottom split' })
vim.keymap.set('n', '<C-k>', '<C-w>k', { desc = 'Jump to top split' })
vim.keymap.set('n', '<C-h>', '<C-w>h', { desc = 'Jump to left split' })
vim.keymap.set('n', '<C-l>', '<C-w>l', { desc = 'Jump to right split' })
vim.keymap.set("i", "<C-BS>", "<C-W>", { desc = 'Delete word backwards' })
vim.keymap.set("i", "<C-h>", "<C-W>", { desc = 'Delete word backwards' })
